version: 2

jobs:
        build:
                machine: true
                steps:
                        - checkout
                        - run: make docker-build
                        - run: make build
                        - run: make phan
                        - run: make test
